let playerOnePoints = 0;
let playerTwoPoints = 0;

let turnScore = 0;

let currentPlayer = 1;


// ----------------------------------------
// Wake up Node.js server
// ----------------------------------------

async function wakeUpServer() {

    // Ask the Node.js server to wake up
    const response =
        await fetch("http://localhost:3000/api/wakeup");

    // Get the response from the server
    const data =
        await response.json();

    console.log(data.message);
}

// Call the wake-up API when the website loads
wakeUpServer();


// ----------------------------------------
// Roll Dice
// ----------------------------------------

async function rollDice() {

    // Ask the Node.js server to roll a six-sided die
    const response =
        await fetch("http://localhost:3000/api/roll/6");

    // Get the JSON response from the server
    const data =
        await response.json();

    // Get the random number generated by the server
    let diceResult = data.roll;

    // Display random number
    document.getElementById("diceResult").value = diceResult;

    // Display message for each roll
    if (diceResult === 1) {

        turnScore = 0;

        document.getElementById("diceMessage").textContent =
            "You rolled a 1 - Sorry turn over!";

    } else {

        turnScore = turnScore + diceResult;

        document.getElementById("diceMessage").textContent =
            "You rolled a " + diceResult + " - keep going!";
    }

    // Display total points from dice rolls
    document.getElementById("dicePoints").value = turnScore;
}


// ----------------------------------------
// Rolling Dice Button
// ----------------------------------------

const button = document.getElementById("rollButton");

button.addEventListener("click", function() {

    rollDice();

});


// ----------------------------------------
// Hold Button
// ----------------------------------------

const holdButton = document.getElementById("holdButton");

holdButton.addEventListener("click", function() {

    if (currentPlayer == 1) {

        playerOnePoints = playerOnePoints + turnScore;

        // Display player 1's preserved score
        document.getElementById("playerOnePoints").value =
            playerOnePoints;

        // Switch to player 2
        currentPlayer = 2;

        // Display message
        document.getElementById("diceMessage").textContent =
            "You pressed the Hold button. Player 1's points are saved. It's Player 2's turn.";

    }

    else {

        playerTwoPoints = playerTwoPoints + turnScore;

        // Display player 2's preserved score
        document.getElementById("playerTwoPoints").value =
            playerTwoPoints;

        // Switch to player 1
        currentPlayer = 1;

        // Display message
        document.getElementById("diceMessage").textContent =
            "You pressed the Hold button. Player 2's points are saved. It's Player 1's turn.";

    }

    turnScore = 0;

    document.getElementById("dicePoints").value = turnScore;

});